title: Manish Reddy
subtitle: Machine Learning & Generative AI Engineer
description: Enterprise-grade Generative AI, LLMs, RAG, MLOps, Cloud

url: "https://ManishR17.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Manish Reddy
  bio: Machine Learning & Generative AI Engineer
  links:
    - label: Email
      icon: fas fa-envelope
      url: mailto:reachmemanish25@gmail.com
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/your-github
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://linkedin.com/in/your-linkedin

header_pages:
  - index.md
  - projects.md
  - experience.md
  - skills.md
  - certifications.md
  - resume.md

search: false
breadcrumbs: false
